### ISSUE TITLE
An UpdateStatus state of 'rollback_completed' gives a false negative

### ISSUE THREAD

**Issue by zaventh** [sudo-bmitch/docker-stack-wait#1]
If any service in the stack has a state of `rollback_completed`, the script assumes failure.

```diff
diff --git a/_scripts/docker-stack-wait.sh b/_scripts/docker-stack-wait.sh
index 333e847..1fee120 100755
--- a/_scripts/docker-stack-wait.sh
+++ b/_scripts/docker-stack-wait.sh
@@ -81,7 +81,7 @@ while [ "$done" != "1" ]; do
           done=2
         fi
         service_done=2
-      elif [ "$state" != "new" -a "$state" != "completed" ]; then
+      elif [ "$state" != "new" -a "$state" != "completed" -a "$state" != "rollback_completed" ]; then
         done=0
         service_done=0
       fi
```

**Comment by zaventh** [comment]
I just realized this is a bit more nuanced. If, for example, the service you are currently trying to deploy fails and you have `failure_action: rollback`, then the current service will enter a `rollback_completed` state and this change would provide a false positive of a successful deployment.

However, without this change if the current deployment succeeds but any other service in the stack has been rolled back, it will fail.

Ideally this script would take a specific service in the swarm to monitor for success instead of checking every service in the stack.

**Comment by sudo-bmitch** [comment]
Thank you for your feedback. I'm thinking about different options to implement this, since some rollbacks may be intentional and a success, and others indicating a failure similar to the pause state. If I don't see an easy way to differentiate, I may just add a command line flag to select the behavior.

Eventually I'm hoping docker will pull stacks into the docker engine as a first class citizen, and implement the detach option on stack commands, which will remove the need for this script.

**Comment by zaventh** [comment]
@sudo-bmitch I agree regarding having this is a first class feature. In the meantime your script has been very useful. I ended up taking a slightly different approach with it since in our CI pipeline we already know the service names we are about to update up front:

```diff
1c1,2
< #!/bin/sh
---
> #!/bin/bash
> # shellcheck disable=SC2001,SC2086,SC2003,SC2046,SC2166,SC2220
13c14
<   echo "$(basename $0) [opts] stack_name"
---
>   echo "$(basename $0) [opts] services"
56c57
< stack_name=$1
---
> IFS=',' read -ra DEPLOY_SERVICES <<< $1
62c63
<   for service_id in $(docker stack services -q "${stack_name}"); do
---
>   for service in "${DEPLOY_SERVICES[@]}"; do
64,65c65
<     service=$(docker service inspect --format '{{.Spec.Name}}' "$service_id")
<     replicas=$(docker service ls --format '{{.Replicas}}' --filter "id=$service_id")
---
>     replicas=$(docker service ls --format '{{.Replicas}}' --filter "name=$service")
75c75
<       state=$(docker service inspect -f '{{if .UpdateStatus}}{{.UpdateStatus.State}}{{else}}new{{end}}' "$service_id")
---
>       state=$(docker service inspect -f '{{if .UpdateStatus}}{{.UpdateStatus.State}}{{else}}new{{end}}' "$service")
77c77
<       if [ "$state" = "paused" ]; then
---
>       if [ "$state" = "paused" -o "$state" = "rollback_started" -o "$state" = "rollback_completed" ]; then
99d98
<  
```

```sh
Updating service [redacted] (id: 8fky6j9chvr34wlphrq2ay2sg)
Service [redacted] is updating
Service [redacted] is replicating 2/1
Service [redacted] is completed
```

Our stack has twelve services and with this approach only the services supplied will be monitored which is typically only one. If the service fails to deploy or the healthcheck fails and a rollback is initiated, the script will also trigger a failure so our pipeline can be notified.

**Comment by sudo-bmitch** [comment]
Have a look at the redesign and let me know if you have any other issues. Thanks again for your report.
