### ISSUE TITLE
Not waiting for the stack to be removed

### ISSUE THREAD

**Issue by jeff-cook** [sudo-bmitch/docker-stack-wait#12]
I'm running into an issue where the script is not waiting for the stack to be removed after `docker stack rm <STACK>` is run. 

I know a bit of an odd use case, but in testing I stand up a stack then remove it before standing up again. However, without waiting for the stack to fully remove the next deploy fails because the stack is still being removed.

**Comment by sudo-bmitch** [comment]
Hi @jeff-cook. That's not a use case I designed this script to handle. It could probably be added, but watching for a stack to be deleted should be a short loop similar to:

```
while ! docker stack services ${stack_name} 2>&1 | grep -q 'Nothing found in stack:'; do sleep 5; done
```

**Comment by sudo-bmitch** [comment]
Closing since this is easy enough to do outside of this script.
