### ISSUE TITLE
Exit with error code 1 if wrong stack name is supplied

### ISSUE THREAD

**Issue by binaryfire** [sudo-bmitch/docker-stack-wait#17]
Would it be possible to make the script exit with code 1 if the wrong stack name is supplied? Currently the message "Nothing found in stack: xxx" is printed but the exit code is 0.

**Comment by sudo-bmitch** [comment]
Done. The `Nothing found in stack: xxx` comes from `docker stack services xxx` but since they weren't exiting with a non-zero code, this was just processing an empty list. That will now fail.

**Comment by binaryfire** [comment]
@sudo-bmitch Nice, thanks!

**Comment by binaryfire** [comment]
@sudo-bmitch Any chance of a new release tag? I like to pin releases for security

**Comment by sudo-bmitch** [comment]
> @sudo-bmitch Any chance of a new release tag? I like to pin releases for security

Done.
