### ISSUE TITLE
Script hangs at docker service logs

### ISSUE THREAD

**Issue by s4ke** [sudo-bmitch/docker-stack-wait#22]
First of all, thanks for this awesome little script.

Recently we are getting some CD failures related to usage of the `-p lines` where the command does not finish.

This seems to be an issue with the docker service logs command (e.g. see https://github.com/moby/moby/issues/41733). While unfortunate, I was thinking about whether this is something that could be addressed by docker-stack-wait.

What I am suggesting is to introduce a change along the lines of this:

```
print_service_logs() {
  if [ "$opt_p" != "0" ]; then
    service_ids=$(get_service_ids)
    for service_id in ${service_ids}; do
      timeout $TIMEOUT_VALUE docker service logs --tail $opt_p "$service_id"
    done
  fi
}
```

Options to do this are:

1. Use the timeout value set by `-t` for `$TIMEOUT_VALUE`, if not set, either use some high default, ore disable the timeout functionality
2. Create a new flag that controls the timeout behaviour

Happy to create a PR for this functionality if this is something that sounds reasonable.

**Comment by sudo-bmitch** [comment]
Hi @s4ke. Thanks for the suggestion. I've added this with #23. Give it a try and let me know if you still have any issues.

**Comment by s4ke** [comment]
Tyvm. Will keep an eye out for this and report back.

**Comment by s4ke** [comment]
The errors seem to have stopped. Tyvm for the quick fix.
