### ISSUE TITLE
Paused state results in an failure

### ISSUE THREAD

**Issue by DRoet** [sudo-bmitch/docker-stack-wait#6]
Hi,

First of, thanks for the script. however I am encountering an issue when updating my stack causing flakiness in my CI.

using docker (`18.09.5`)
./docker-stack-wait.sh -t 120 frontend

Service frontend_test state: updating
Service frontend_foo state: new
Service frontend_bar state: updating
Service frontend_server state: updating
Service frontend_bar state: replicating 0/1
Service frontend_test state: paused
Service frontend_bar state: updating
Service frontend_server state: paused

this only happens sometimes and the services seem to update fine (no rollback failure), so I'm not sure why the paused state is considered a failure.

any ideas?

**Comment by sudo-bmitch** [comment]
Does frontend_server go back from paused to updating or complete when you look at `docker service inspect frontend_server -f '{{.UpdateStatus.State}}'`. Paused is the default response to a failed deploy which you can configure, e.g.: https://docs.docker.com/compose/compose-file/#update_config

**Comment by DRoet** [comment]
I'll have to wait for another flaky run, but usually when I re-run the same job (the stack update + stack wait) it gives an instant state: `new` (without even updating) so it seems like it only stays paused for a split second.

I'll try the command next time and come back to you with the results

**Comment by sudo-bmitch** [comment]
Try to run just the stack-wait command without the stack update (the stack update will restart the deploy and clear out any paused state). It sounds like your healthcheck is initially failing but eventually succeeding after a few retries. You can adjust your healthcheck thresholds to only have it pause the deploy on a more persistent failure.

**Comment by DRoet** [comment]
Ok I ran the command after the failing (paused) one:

```
"UpdateStatus": {
     "State": "paused",
     "StartedAt": "2019-04-18T15:15:44.040747072Z",
     "Message": "update paused due to failure or early termination of task w8rmczsnb8hm947vickxypcoh"
}
```

However the service seems to be running fine and has: 

```
"UpdatedAt": "2019-04-18T15:16:00.216058821Z",
```

The UpdateAt time is bout 5 seconds after pausing, which is kind of odd, maybe it is just the first healthcheck that failed? I'll try messing around with healthcheck thresholds and update_config..

**Comment by sudo-bmitch** [comment]
Looks like the docker-stack-wait script properly reported the failure, so I'll mark this one as closed.

The `UpdatedAt` can be changed by lots of things, and is probably impacted by tasks being recreated as it retries starting the containers. The `UpdateStatus` is reporting how the deployment is progressing, and can be adjusted with the update_config in the compose file.
